[features]
seeds = false
skip-lint = false
[programs.localnet]
crowdfunding_tutorial = "FrUhnZocqqx8ChuspvoxhqUEupEH1nAZVx6C7TEnfuor"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
